config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  resource :session
  resource :user

  get "/login", to: "users#new"
  post "/login", to: "users#create"
  get "/logout", to: "sessions#logout"
  delete "/logout", to: "sessions#destroy"

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, format: { with: /\A(?!.*\b(Trump|Kamala)\b).*/, message: "should not be about the election" }, length: { minimum: 1 }
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :content, format: { with: /\A(?!.*\b(Trump|Kamala)\b).*/, message: "should not be about the election" }, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.commenter = current_user.username
    @comment.save
    @post.count += 1
    @post.save
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
    if !user_signed_in?
      redirect_to "/login"
    end
  end

  def show
    @post = Post.find(params[:id])
    if !user_signed_in?
      redirect_to "/login"
    end
  end

  def new
    @post = Post.new
    if !user_signed_in?
      redirect_to "/login"
    end
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user.username
    @post.count = 0

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.find_by(username: params[:username])
      login user
      redirect_to root_path
    end
  end

  def destroy
    logout current_user
    redirect_to "/logout"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user = User.find_by(user_params)
      login user
      redirect_to root_path
    else
      @user = User.new(user_params)
      if @user.save
        login @user
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    # @user = User.new(user_params)
    # if @user.save
    #   login @user
    #   redirect_to root_path
    # else
    #   render :new, status: :unprocessable_entity
    # end

    # if user = User.find_by(user_params)
    #   login user
    #   redirect_to root_path
    # end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @post.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= button_to "Log out", "/logout", method: :delete %>

<% if user_signed_in? %>
    <p>Signed in as: <%= current_user.username %><p>
<% end %>

<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <div>content: <%= post.content %></div>
      <div>author: <%= post.author %></div>
      <div>comments: <%= link_to post.count, post %></div>
      <div>last updated: <%= post.updated_at %></div>
    </li>
    <p></p>
  <% end %>
</ul>

<%= link_to "Create new post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
    <% @post.errors.full_messages_for(:content).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<p><%= @post.content %></p>
<p>Author: <%= @post.author %></p>
<p>Comments: <%= @post.count %></div>
<p>Last updated: <%= @post.updated_at %></p>

<% if current_user.username == @post.author %>
  <li><%= link_to "Edit", edit_post_path(@post) %></li>
  <li><%= link_to "Destroy", post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
<% end %>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<p></p>
<%= link_to "Back to posts", root_path %>

app/views/users/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: user_path do |form| %>
    <div>
        <%= form.label :username %><br>
        <%= form.text_field :username %>
    </div>

    <div>
        <%= form.submit "Log in" %>
    </div>
<% end %>